### ISSUE TITLE
More Summer Pre-college Suggestions

### ISSUE THREAD

**Issue by ex0dus-0x** [JustinChavez/Pre-College-Opportunities#1]
Love this repository. I do have a few more suggestions on what to add for pre-college opportunities.

* [NYU ASPIRE](http://www.sps.nyu.edu/academics/hsacademy/summer-programs/aspire.html)
* [Cooper Union STEM](https://cooper.edu/engineering/summer-stem)

**Comment by JustinChavez** [comment]
Thanks! Those opportunities look great! Just added.
